### PR TITLE
Active Directory groups, custom username field, null groups

### PR DESCRIPTION
**Pull request by marknduncan**
Hello,

This is my first pull request so please let me know if I am not following GitHub etiquette.

I have a few bug fixes for the project.  One of these has already been proposed by @jtpenny concerning Windows groups so I just want to make sure he gets credit for that fix. I have tested it and it works in our environment with AD (thank you!)

The other part of that commit is for fixing a bug where the user specified username field is set to the key 'username' instead of the function for getting the username.

Lastly, there is a bug where an offset error occurs in the retrieveByCredentials() function if a non-existent username is passed to that function, so it can't find the groups (returns null) which causes problems further down the line in the InfoCollection.

Let me know if you have any questions. Thanks for this project, it is extremely useful!

### CODE REVIEW

**Comment by strebl** [comment]
Hi @mduncan02 
Thank you for your work!
Can you apply the StyleCI patch?
There are many changes just because your code style is different.
That would be great!

**Comment by marknduncan** [comment]
No problem! I have applied the StyleCI patch, let me know if you need anything else.

**Comment by strebl** [comment]
It seems there is something wrong with your bugfix.
I have a simple test setup:

``` php
Route::get('/', function () {
    Auth::logout();
    if(Auth::attempt(['username' => 'existinguser', 'password' => 'secret']))
    {
        dd(Auth::user()->toArray());
    }
    else {
        return "failed";
    }
});
```

If I use your changes I get following error:

```
ErrorException in LdapAuthUserProvider.php line 136:
Undefined variable: infoCollection
```

That happens even if I'm testing with an non-existing user.

I have recursive_group set to false.

If I set recursive_group to true, it works.

But I don't get any errors without your fix. I tried following combinations without an error:

| recursive_group | existing user |
| --- | --- |
| true | true |
| false | true |
| true | false |
| false | false |

Can you show me your test setup?

**Comment by marknduncan** [comment]
Interesting, I think  Scrutinizer actually picked that up as well, let me do some testing and see if I can't figure out what happened there. I will post my setup here as well

**Comment by marknduncan** [comment]
Ok I think it was just a syntax issue, I believe I have fixed it now. Could you please try your tests again? Thanks!

**Comment by strebl** [comment]
Okay, now I get no errors.
But login an user only works if `recursive_groups` is set to true.
Again, I tested all 4 combinations which my old code without any errors. Can you show me an example which throws an error with the old code and works with the new code?

**Comment by marknduncan** [comment]
Sorry yes, I have recursive_groups set to true in my config. Let me do more testing with the different combinations of config options. I am working on a fairly large project at the moment so I will re-request the pull once I've done better testing. Talk with you again soon!

**Pull request closed without merging**
