### PR TITLE
Active directory groups patch

### PR DESCRIPTION
**Pull request by jtpenny**

### CODE REVIEW

**Comment by strebl** [comment]
Hi @jtpenny 

Can you give me some hints what doesn't work at the moment and what you are fixing?

**Comment by jtpenny** [comment]
Hi @strebl 

We're connecting to Windows Server 2008 R2 and need to pull a user's groups via Auth::user()->groups for role based access to areas of the app. Currently Auth::user()->groups returns groups from Windows Server 2008 R2 with the first three letters chopped off because the code is attempting to remove DC= from the front of the string. My update checks to see if the string begins with DC= and removes the first three characters only in that situation.

**Comment by strebl** [comment]
Will look into that tomorrow. Thanks for the explanation!

**Comment by strebl** [comment]
@jtpenny Sorry for not responding over 13 days....
I just released the laravel 5.1 version and I'm now ready to merge your pull request.
However there merge conflicts now.
Do you mind to update your PR or create a new one?

**Pull request closed without merging**
